name: Terraform Lint Check

on:
  push:
    paths:
      - '**/*.tf'
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  terraform-lint:
    name: Terraform Format & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init -backend=false

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest

      - name: Run tflint
        run: tflint
